title: Svenaldo Blog
email: info@svenaldo.de
description: >-
  IT, Tech, Dev, Maker, Hacking
baseurl: ""
url: "https://svenaldo.de"
twitter_username: svenaldo
github_username:  svenaldo

# Build settings
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed